### ISSUE TITLE
The enderio telepad has stopped working properly

### ISSUE THREAD

**Issue by Questwalker** [Kinetic-Development/Mythic-Novus#1]
The enderio telepad has been working fine, until recently. Now, whenever i try to use it, no matter the location, the teleport is blocked. The developer said this can be caused by a mod purposely blocking it but i wouldn't know what it is.

Telepad coords(just incase its needed) -3421 22 -6996

Modpack: Mythic Novus

**Comment by SleepingTea98** [comment]
This issue has now been fixed
